"""Add avaliacao instrutores

Revision ID: 11dc3e14f405
Revises: 6ee503d2323f
Create Date: 2026-08-14 07:52:55.788470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11dc3e14f405'
down_revision = '6ee503d2323f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campanhas_avaliacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('is_ativa', sa.Boolean(), nullable=False),
    sa.Column('is_obrigatoria', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('respostas_avaliacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campanha_id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('instrutor_id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('data_resposta', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['campanha_id'], ['campanhas_avaliacao.id'], ),
    sa.ForeignKeyConstraint(['instrutor_id'], ['instrutores.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('respostas_avaliacao')
    op.drop_table('campanhas_avaliacao')
    # ### end Alembic commands ###
