"""add publico_alvo and ativo to questionario

Revision ID: 6ee503d2323f
Revises: b04a281525f8
Create Date: 2026-08-14 07:31:29.805630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ee503d2323f'
down_revision = 'b04a281525f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questionarios', sa.Column('publico_alvo', sa.String(length=50), nullable=False, server_default='todos'))
    op.add_column('questionarios', sa.Column('ativo', sa.Boolean(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questionarios', 'ativo')
    op.drop_column('questionarios', 'publico_alvo')
    # ### end Alembic commands ###
