"""Transform Avaliacao Instrutor em Avaliacao Modulo com Sigilo

Revision ID: 7fe2da43c113
Revises: 33dc3e14f405
Create Date: 2026-08-19 15:21:17.305778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fe2da43c113'
down_revision = '33dc3e14f405'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('respostas_avaliacao_geral',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campanha_id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('token_sigilo', sa.String(length=100), nullable=False),
    sa.Column('nota_organizacao', sa.Integer(), nullable=False),
    sa.Column('nota_tecnologia', sa.Integer(), nullable=False),
    sa.Column('nota_corpo_alunos', sa.Integer(), nullable=False),
    sa.Column('nota_direcao', sa.Integer(), nullable=False),
    sa.Column('nota_satisfacao_geral', sa.Integer(), nullable=False),
    sa.Column('comentarios_gerais', sa.Text(), nullable=True),
    sa.Column('data_resposta', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campanha_id'], ['campanhas_avaliacao.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('respostas_avaliacao_geral', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_respostas_avaliacao_geral_token_sigilo'), ['token_sigilo'], unique=False)

    op.create_table('controle_preenchimento_avaliacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campanha_id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('data_preenchimento', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['campanha_id'], ['campanhas_avaliacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    with op.batch_alter_table('respostas_avaliacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_sigilo', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('nota_relacionamento', sa.Integer(), server_default='3', nullable=False))
        batch_op.add_column(sa.Column('nota_dominio', sa.Integer(), server_default='3', nullable=False))
        batch_op.add_column(sa.Column('nota_relevancia', sa.Integer(), server_default='3', nullable=False))
        batch_op.alter_column('aluno_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('nota',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_respostas_avaliacao_token_sigilo'), ['token_sigilo'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('respostas_avaliacao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_respostas_avaliacao_token_sigilo'))
        batch_op.alter_column('nota',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('aluno_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('nota_relevancia')
        batch_op.drop_column('nota_dominio')
        batch_op.drop_column('nota_relacionamento')
        batch_op.drop_column('token_sigilo')

    op.drop_table('controle_preenchimento_avaliacao')
    with op.batch_alter_table('respostas_avaliacao_geral', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_respostas_avaliacao_geral_token_sigilo'))

    op.drop_table('respostas_avaliacao_geral')
    # ### end Alembic commands ###
